site_name: RentBnB System Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Overview: index.md
  - Modules: modules.md
  - Permissions: permissions.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - attr_list
  - toc:
      permalink: true